### ISSUE TITLE
[Bug]: World not loading

### ISSUE THREAD

**Issue by bLlind** [FamroFexl/Circumnavigate#29]
### Describe the Bug

World loading screen would not progress after 6% although this value still can vary from 1% to 6%

### Mod version(s) affected

0.3 (Other Version not checked)

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.20.4

### Other mods used

Sodium, Iris, Lithium, indium, FLK (Fabric Language Kotlin), Immediatelyfast

### To Reproduce (If applicable)

Install The Mods mentioned (it probably doesn't matter since i've tested it without them, but who knows)

### Additional Information

Live log  -
```
null[13:24:48] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.16.0
[13:24:48] [main/INFO]: Loading 80 mods:
	- circumnavigate 0.3
	- entityculling 1.7.1
	- fabric-api 0.97.1+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.87+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
	   |-- fabric-dimensions-v1 2.1.63+6605d1a84f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.21+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.6+d331d3144f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabric-language-kotlin 1.12.3+kotlin.2.0.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.4
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.0
	   \-- mixinextras 0.4.0
	- immediatelyfast 1.3.2+1.20.4
	   \-- net_lenni0451_reflect 1.3.4
	- indium 1.0.31+mc1.20.4
	- iris 1.7.2+mc1.20.4
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- java 17
	- lithium 0.12.1
	- minecraft 1.20.4
	- sodium 0.5.8+mc1.20.4
[13:24:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/ModrinthApp/meta/libraries/net/fabricmc/sponge-mixin/0.15.0+mixin.0.8.7/sponge-mixin-0.15.0+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[13:24:49] [main/INFO]: Compatibility level set to JAVA_17
[13:24:49] [main/WARN]: Option 'mixin.entity.collisions.fluid' requires 'mixin.experimental.entity.block_caching.fluid_pushing=false' but found 'true'. Setting 'mixin.entity.collisions.fluid=false'.
[13:24:49] [main/INFO]: Loaded configuration file for Lithium: 129 options available, 2 override(s) found
[13:24:49] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[13:24:49] [main/WARN]: Force-disabling mixin 'experimental.chunk_tickets.ChunkTicketManagerMixin' as rule 'mixin.experimental.chunk_tickets' (added by user configuration) disables it and children
[13:24:49] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:24:49] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:24:49] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:24:49] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[13:24:49] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[13:24:49] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:24:49] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:24:49] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[13:24:50] [main/INFO]: Searching for graphics cards...
[13:24:50] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.0).
[13:24:50] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce RTX 3050 Laptop GPU, version=DriverVersion=32.0.15.6603]
[13:24:50] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) UHD Graphics, version=DriverVersion=31.0.101.5333]
[13:24:50] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[13:24:50] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[13:24:55] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 133 milliseconds
[13:24:57] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:24:57] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[13:24:58] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[13:24:58] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[13:24:58] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[13:24:59] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[13:24:59] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2
[13:24:59] [Render thread/INFO]: OpenGL Version: 3.2.0 NVIDIA 566.03
[13:24:59] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] This version doesn't have an update index, skipping.
[13:24:59] [Render thread/INFO]: Initializing ImmediatelyFast 1.3.2+1.20.4 on NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 (NVIDIA Corporation) with OpenGL 3.2.0 NVIDIA 566.03
[13:24:59] [Render thread/INFO]: Found Iris/Oculus 1.7.2+mc1.20.4. Enabling compatibility.
[13:24:59] [Render thread/INFO]: Debug functionality is disabled.
[13:24:59] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[13:24:59] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[13:24:59] [Render thread/WARN]: Removed resource pack file/MandalasGUI_Dakmode_Vanilla1.20.4.zip from options because it doesn't seem to exist anymore
[13:25:00] [Render thread/INFO]: Hardware information:
[13:25:00] [Render thread/INFO]: CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
[13:25:00] [Render thread/INFO]: GPU: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 566.03)
[13:25:00] [Render thread/INFO]: OS: Windows 11 (10.0)
[13:25:00] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, circumnavigate, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, immediatelyfast, indium, iris, lithium, sodium
[13:25:00] [Worker-Main-11/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[13:25:02] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[13:25:02] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[13:25:03] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on S�uchawki (Realtek(R) Audio)
[13:25:03] [Render thread/INFO]: Sound engine started
[13:25:03] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[13:25:03] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[13:25:03] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[13:25:03] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[13:25:03] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[13:25:03] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[13:25:03] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[13:25:03] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[13:25:03] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:25:04] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[13:25:04] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[13:25:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:25:04] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:25:04] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[13:25:04] [Render thread/INFO]: Creating pipeline for dimension minecraft:overworld
[13:25:09] [Render thread/INFO]: Loaded 7 recipes
[13:25:09] [Render thread/INFO]: Loaded 1271 advancements
[13:25:20] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 2.028 ms
[13:25:20] [Server thread/INFO]: Starting integrated minecraft server version 1.20.4
[13:25:20] [Server thread/INFO]: Generating keypair
[13:25:22] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:25:23] [Render thread/INFO]: Preparing spawn area: 0%
[13:25:23] [Render thread/INFO]: Preparing spawn area: 0%
[13:25:23] [Render thread/INFO]: Preparing spawn area: 0%
[13:25:24] [Render thread/INFO]: Preparing spawn area: 1%
[13:25:24] [Render thread/INFO]: Preparing spawn area: 3%
[13:25:25] [Render thread/INFO]: Preparing spawn area: 5%
[13:25:25] [Worker-Main-9/ERROR]: Caught exception in thread Thread[Worker-Main-9,5,main]
java.lang.NoSuchMethodError: 'com.fexl.circumnavigate.core.WorldTransformer net.minecraft.class_1941.getTransformer()'
	at net.minecraft.class_5329.handler$zzo000$circumnavigate$init(class_5329.java:541) ~[client-intermediary.jar:?]
	at net.minecraft.class_5329.<init>(class_5329.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_39456(class_1941.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_8587(class_1941.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_18026(class_1941.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_1948.method_8661(class_1948.java:508) ~[client-intermediary.jar:?]
	at net.minecraft.class_3754.method_12107(class_3754.java:453) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_17033(class_2806.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:671) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:660) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[13:25:25] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:26] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:26] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:27] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:27] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:28] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:28] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:29] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:29] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:30] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:30] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:31] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:31] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:32] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:32] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:33] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:33] [Worker-Main-8/ERROR]: Caught exception in thread Thread[Worker-Main-8,5,main]
java.lang.NoSuchMethodError: 'com.fexl.circumnavigate.core.WorldTransformer net.minecraft.class_1941.getTransformer()'
	at net.minecraft.class_5329.handler$zzo000$circumnavigate$init(class_5329.java:541) ~[client-intermediary.jar:?]
	at net.minecraft.class_5329.<init>(class_5329.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_39456(class_1941.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_8587(class_1941.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_18026(class_1941.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_1948.method_8661(class_1948.java:508) ~[client-intermediary.jar:?]
	at net.minecraft.class_3754.method_12107(class_3754.java:453) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_17033(class_2806.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:671) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:660) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[13:25:33] [Worker-Main-5/ERROR]: Caught exception in thread Thread[Worker-Main-5,5,main]
java.lang.NoSuchMethodError: 'com.fexl.circumnavigate.core.WorldTransformer net.minecraft.class_1941.getTransformer()'
	at net.minecraft.class_5329.handler$zzo000$circumnavigate$init(class_5329.java:541) ~[client-intermediary.jar:?]
	at net.minecraft.class_5329.<init>(class_5329.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_39456(class_1941.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_8587(class_1941.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_1941.method_18026(class_1941.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_1948.method_8661(class_1948.java:508) ~[client-intermediary.jar:?]
	at net.minecraft.class_3754.method_12107(class_3754.java:453) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_17033(class_2806.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:671) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:660) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[13:25:33] [Render thread/INFO]: Preparing spawn area: 6%
[13:25:34] [Render thread/INFO]: Preparing spawn area: 6%

```
Wrapping Presets -
Minimum X - -100
Maximum X - 100
Minimum Z  - -100
Maximum Z - 100

Any setting below is not touched

**Comment by Skidamek** [comment]
Try 0.4.1, this is alpha software it's changing quickly, this may have been fixed
